config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
  resources :users #Al parecer importa la posición 
  root 'pages#index' # root es buena páctica, también se podría: get '/', to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  #Relaciones
  belongs_to :user
  #index
  default_scope { order(updated_at: :desc)} #COLOCAR LOS MÁS ACTUALIZADOS DE PRIMERO
  #Url amigables
  extend FriendlyId
  friendly_id :title, use: :slugged
  #Paginación
  paginates_per 8
  #Validaciones
  validates :title, presence: true,
                    uniqueness: true,
                    length: { minimum: 10, maximum: 75 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  #Relaciones
  has_many :articles
  #Index
  default_scope { order(updated_at: :desc)} #COLOCAR LOS MÁS ACTUALIZADOS DE PRIMERO
  #Auntenticaciones de los usuarios en Devise
  validates :name, :lastname, :age, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user_params| user_params.permit(:email,
                                                               :password,
                                                               :current_password,
                                                               :password_confirmation,
                                                               :name,
                                                               :lastname,
                                                               :age)}
   devise_parameter_sanitizer.permit(:account_update) { |user_params| user_params.permit(:email,
                                                                      :password,
                                                                      :current_password,
                                                                      :password_confirmation,
                                                                      :name,
                                                                      :lastname,
                                                                      :age)}
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [ :edit, :update, :destroy]


  def index
    @recentUsers = User.all.take(3)
    @countArticles = Article.count #Cuéntame cuántos artículos hay
    @recentArticles = Article.all.take(3) #Instancia en la variable @recentArticles los 3 artículos más recientes y luego los recorres e imprimes
    @articles = Article.all.page params[:page]
    #Pedir los campos específicos: @articles = Article.select("id, title, body")
    
    #SEARCH
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @articles = Article.where("title ILIKE ?", "%#{@title}%").page params[:page]
    end

  end

  def show
    @article = Article.friendly.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Tu articulo ha sido creado" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Tu articulo ha sido creado" }
        format.json { render :show, status: :crated, location: @article}
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Tu articulo ha sido eliminado" }
      format.json { head :no_content}
    end
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params 
    params.require(:article).permit(:title,
                                    :body,
                                    :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  def show
    @user = User.find(params[:id])
    @articles = Article.all
  end

  def edit
  end

  def update
  end

  private

  def set_user 
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :lastname,
                                 :age, :email, :password,
                                 :current_password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= simple_form_for @article, local: true do |f| %>
  <div class="form-group">
    <%= f.input :title, placeholder: "Minimun 8, máximun 75 characters" %>
  </div>
  <div class="form-group">
    <%= f.input :body, class: 'form-control', placeholder: "Minimun 10 characters" %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.button :submit, class:"btn btn-primary btn-sm" %>
    <%= link_to 'Cancel', articles_path, class:"btn btn-danger btn-sm ml-2"%>
  </div>
  <% end %>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="text-center">Editar artículo</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="content">
  <div class="content-articles">
    <div class="content-articles-user">
      <h3>Welcome, <%= current_user.name %></h3>
      <%= link_to "New article", new_article_path, class:"btn btn-primary btn-sm" %>
    </div>
    <!-- SEARCH ARTICLE -->
    <div class="search-body">
      <%= simple_form_for :search, url: articles_path, method: "GET", html: { class: 'form-control-lg d-flex' } do |f| %>
      <%= f.input :title, input_html: {value: ""}, label: false, placeholder: "Search an article here here..", class:"search" %>
      <%= f.submit 'search',  class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
    <!-- SEARCH ARTICLE -->
    <!-- ARTICLES.COUNT == 0 -->
    <% if @countArticles == 0 %>
      <%= image_tag("hero-img.svg", class: "content-articles-img") %>
      <h2 class="content-articles-none">Sorry, there are no articles.</h2>
      <div class="content-articles-button">
        <%= link_to "New article", new_article_path, class:"btn btn-primary" %>
      </div>
    <% else %>
      <% if @articles.blank? %>
        <%= image_tag("hero-img.svg", class: "content-articles-img") %>
        <h2 class="content-articles-none">Sorry, we didn't find an article related to <span class="primary"><%= @title %></span></h2>
      <% end %>
    <% end %>
    <!-- ARTICLES.COUNT == 0 -->
    <% @articles.each do |article| %>
    <div class="article">
      <div class="article-title">
        <h4><%= link_to article.title.upcase, article %> <i class="fa fa-link"></i></h4>
      </div>
      <div class="article-info">
        <div class="article-info-user">
          <small><i class="fa fa-user"></i></small> <span><small><%= article.user.name %> <%#= article.user.lastname %></small></span>
        </div>
        <div class="article-info-date">
          <small><i class="fas fa-calendar"></i></small> <span><small><%=article.created_at.to_date.to_formatted_s(:long)%></small></span>
        </div>
      </div>
      <div class="article-body">
        <% @firstWords = article.body.split(" ").first(35).join(" ") %> <!--Obtener las primeras 30 palabras-->
        <p><%= @firstWords %> ...</p>
      </div>
    </div>
    <%end%>
    <%= paginate @articles, theme: 'twitter-bootstrap-4' %>
  </div>
  <div class="content-user">
    <div class="user">
      <h5>Welcome, <%= current_user.name %></h5>
      <!-- <p>Hemos encontrado <%= @count %> artículos para tí.</p> -->
      <div class="user-buttons">
        <div class="user-buttons-view">
          <%= link_to "My Profile", user_path(current_user), class:"btn btn-primary btn-sm" %>
        </div>
        <div class="user-buttons-new">
          <%= link_to "New Article", new_article_path, class:"btn btn-primary btn-sm" %>
        </div>
      </div>
    </div>
    <div class="users">
      <h5>Recent Users</h5>
      <% @recentUsers.each do |user| %>
        <div class="user-active">
          <p><%= link_to user.name, user_path(user) %> <small><%= user.age %> años</small> </p> 
          
        </div>
      <%end%>
    </div>
    <div class="recent-articles">
      <h5>Recent Articles</h5>
      <% if @count == 0 %>
      <h2 class="recent-articles-none">Create a article!</h2>
    <% end %>
      <% @recentArticles.each do |article| %>
        <div class="recent-article">
          <%= link_to article.title, article_path(article) %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="text-center">Nuevo artículo</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="show-article">
  <img class="show-article-img" src="https://source.unsplash.com/600x300/?nature,water" alt="">
  <div class="show-article-header">
    <div class="show-article-header-title">
      <h1 class="article-header"><%= @article.title %></h1>
    </div>
    <div class="show-article-header-author">
      <p class="author">Por <%= @article.user.name %></p>
    </div>
    <div class="show-article-header-options">
      <%= link_to 'Back', articles_path, class:"btn btn-light btn-sm" %>
      <% if user_signed_in? and @article.user.email == current_user.email %>
          <%= link_to 'Edit'.html_safe, edit_article_path(@article), class:"btn btn-warning btn-sm" %>
          <%= link_to @article, class:"btn btn-danger btn-sm", method: :delete, data: { confirm: '¿Estás seguro de que quieres eliminar este artículo?' } do %>
            <span>Delete</span>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
           
<div class="show-content">
  <p><%= (raw @article.body) %></p>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-mi">
  <div class="container">
    <%= link_to image_tag("logo.svg", class: 'mt-1 img-fluid logo-img'), root_path, class: 'logo mr-3' %>
      
    <% if user_signed_in? %>
      <div class="search-nav">
        <%= simple_form_for :search, url: articles_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :title, input_html: {value: ""}, label: false, placeholder: "Search an article here here..", class:"search" %>
        <%= f.submit 'search',  class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    <%end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon d-inline">
      <% if user_signed_in? %>
        <%= link_to('Log out', destroy_user_session_path, class: 'btn btn-outline-primary btn-sm', method: :delete) %>
      <% else %>
        <%= link_to 'Log in', user_session_path, class: 'btn btn-outline-primary btn-sm' %>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-sm' %>
      <% end %>
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Articles', articles_path, class:"nav-link" %>
        </li>
      <% end %>
      <li class="nav-item active">
        <a href="mailto:zabalafmiguel@hotmail.com" class="nav-link">Contact</a>
      </li>
      <!-- <li class="nav-item">
        <a href="#" class="nav-link">Posts</a>
        <%# link_to 'Posts', articles_path, class: 'nav-link' %>
      </li> -->
      <li class="nav-item">
        <p class="nav-link">|</p>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.name, user_path(current_user), class:"nav-link user" %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to('Log out', destroy_user_session_path, class: 'btn btn-outline-primary btn-sm', method: :delete) %>
        </li>
      <% else %>
        <li class="nav-item d-flex align-items-center">
          <%= link_to 'Log in', user_session_path, class: 'btn btn-outline-primary btn-sm' %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blog - ROR - Miguel Zabala</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <!-- <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
      <%= yield %>
    </div>

    <script src="https://kit.fontawesome.com/bc8dc34fc7.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="hero">
  <%= image_tag("hero-bg.svg", class: "hero-bg") %>
  <div class="hero-info">
    <div class="hero-info-title">
      <h1>What you think?</h1>
    </div>
    <div class="hero-info-description">
      <p>Designed and developed by Miguel Zabala Figueroa under the Ruby on Rails framework, Bootstrap + SASS.</p>
      <span class="mt-0">You must register to see the articles</span>
    </div>
    <div class="hero-bottom">
      <a href="<%= articles_path %>" class="hero-bottom-link">Artículos</a>
    </div>
  </div>
  <%= image_tag("hero-img.svg", class: "hero-img") %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1 class="mt-3">Profile</h1>
<div class="my-acount">
  <div class="my-acount-container">
    <%= image_tag("user.png", class: "my-acount-container-img") %>
  </div>
  <div class="my-acount-info">
    <h2><%= @user.name %> <%= @user.lastname %></h2>
  </div>
</div>

<div class="links">
  <%= link_to "Back", articles_path, class:"btn btn-danger btn-sm" %>
  <% if @user.id == current_user.id %>
    <%= link_to "Edit Profile", edit_user_path(current_user), class:"btn btn-primary btn-sm" %>
  <% end %>
</div>
<h3>Articles</h3>
<% @articles.each do |article| %>
  <% if article.user_id == @user.id %>
    <div class="my-article">
      <%=  link_to article.title, article_url(article) %>
    </div>
  <% end %>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>